### ISSUE TITLE
Problem with project 6

### ISSUE THREAD

**Issue by SelaOAL** [Autodesk-Forge/forge-boilers.nodejs#3]
I'm trying to run project number 6.

I set the CallBack URL in the app to: `http://localhost:3000/api/forge/callback/oauth`
And the environment variables for the id and secret. 
And: `set HOST_URL=http://localhost:3000`

But when I navigate to http://localhost:3000 and press `User Data` I get a popup with the following message in it:

> {"developerMessage":"The required parameter(s) client_id not present in the request","userMessage":"","errorCode":"AUTH-008","more info":"http://developer.api.autodesk.com/documentation/v1/errors/AUTH-008"}

Did I miss something?

**Comment by jeremytammik** [comment]
did you set the environment variables FORGE_CLIENT_ID and FORGE_CLIENT_SECRET as described in the readme?

**Comment by SelaOAL** [comment]
Yes.

**Comment by leefsmp** [comment]
Did you try to run the server using "npm start" ? The error you get looks very much like you don't have the required environment variables set properly as Jeremy suggested above... to make sure you can add a simple "console.log(FORGE_CLIENT_ID)" in the server code

**Comment by SelaOAL** [comment]
I just tried to run it with `npm start` and I get in the browser: `Cannot GET /` and nothing in the consoles.  (one console is with the `npm run build-dev` and the other runs `npm start` or `npm run dev`)

And I double checked that I have the environment variables set with the command `set | more` and they're there.

**Comment by RThoman** [comment]
I was intrigued by SelaOAL's post because I had exactly the same problem with Boiler 6.  

Further study established that I did not notice that the CLIENT_ID variables for Boiler 6 are slightly different than some of the other boilers.  Note that instead of `FORGE_CLIENT_ID` the setting is` FORGE_DEV_CLIENT_ID` and instead of `FORGE_CLIENT_SECRET` the setting is `FORGE_DEV_CLIENT_SECRET`.   You can see these variables referenced in the development.config.js file.  

Philippe notes this difference in his Readme.md notations for Boiler 6.  He recommended creating 2 sets of API Keys, one for DEVELOPMENT and one for PRODUCTION and the above difference relates to this recommendation.  I overlooked his notation the first time I worked with this boiler.  Once I made this adjustment I found I did not get the error similar to yours and that I could authenticate.   Hope this helps.

**Comment by jeremytammik** [comment]
well observed! thank you for pointing it out specifically! yes, you need two separate sets of Forge API keys for dev and prod.

**Comment by jpryne** [comment]
I deployed example #6 directly to Heroku, added the ID & secret from my Forge app, set the HOST_URL and the callback URL, yet am still unable to complete a handshake. Here's a snapshot from my console:
![error-promise](https://user-images.githubusercontent.com/1497564/27205356-1fd099d8-51e5-11e7-90c6-24f1c917c511.png)

**Comment by leefsmp** [comment]
I just updated the ENV vars that need to be defined in the heroku creation page, there was a mistake in the last commit I did which was missing HOST_URL, sorry about that. Please try again. The heroku page should look as follow, then in the console traces you can double check the client is trying to connect to the matching host url.

<img width="545" alt="screen shot 2017-06-16 at 08 01 58" src="https://user-images.githubusercontent.com/4352502/27214001-64da89a0-526a-11e7-8eb4-6ae5df77c761.png">

**Comment by jpryne** [comment]
Thanks for the help, Phillip! I'll give this another try asap..

**Comment by jpryne** [comment]
Still having the same issues. I had already manually set the HOST_URL the first time, so I'm not sure anything is different.

**Comment by jpryne** [comment]
What do you mean when you say we need two sets of API keys? Where do we put the other one? Can we not deploy directly from Github?

**Comment by leefsmp** [comment]
It's definitely working OK now, I just tested it at the moment:

Name of my heroku app is "dm-heroku", so its url is [https://dm-heroku.herokuapp.com](https://dm-heroku.herokuapp.com) (give it a try before I take it down ...), hence my forge config looks as follow (in [https://developer.autodesk.com/myapps](https://developer.autodesk.com/myapps)):

<img width="616" alt="screen shot 2017-06-16 at 22 35 33" src="https://user-images.githubusercontent.com/4352502/27243842-2a6d532c-52e4-11e7-84e9-1fe36b2a4b2a.png">

App Name and website URL can be whatever, but callback URL needs to be an exact match.

The 2 sets of keys is handy when you want to run a DEV and a PROD config of the sample: because a set of keys can only bind to a single callback url, the dev can be [http://localhost:3000/api/forge/callback/oauth](http://localhost:3000/api/forge/callback/oauth) and the PROD [https://whatever.host.you.want.com/api/forge/callback/oauth](https://whatever.host.you.want.com/api/forge/callback/oauth).

Hope that helps
