### ISSUE TITLE
"Enter you Consumer Key and Consumer Secret to get a valid Access token"? What does this mean?

### ISSUE THREAD

**Issue by jpryne** [Autodesk-Forge/forge-boilers.nodejs#6]
> You will need to generate a valid 2-legged OAuth token and upload a model to your account, which you can do using that website for now: https://models.autodesk.io

**Comment by jpryne** [comment]
This note is pretty funny though:

"Sending Consumer key and secret via an http request is not recommended. Be aware of the risk of sending information like this. However, if you are using this tool only once in a while, it should be fine."

**Comment by leefsmp** [comment]
I'm glad this is amusing to you. We created [https://models.autodesk.io](https://models.autodesk.io) to make it easy for a beginner to upload and translate a model with his own set of keys without having to go through all the steps. You can provide your clientId/Secret on that page and it will generate a token for you and you can upload models as well, then use the token on your local machine to load the URN that was generated. What the note means is that it's probably OK to do this couple of times, but if you use that tool everyday, somebody might be tempted to sniff your http traffic and intercept your credentials. Then use them to send jobs to the Forge APIs. Since you will be charged for that, it's probably not desirable.  The best way would be to follow the tutorial at: [https://developer.autodesk.com/en/docs/model-derivative/v2/tutorials/prepare-file-for-viewer/](https://developer.autodesk.com/en/docs/model-derivative/v2/tutorials/prepare-file-for-viewer/ )
